---
- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    update_cache: true

- name: Start service Apache
  ansible.builtin.service:
    name: apache2
    state: started

- name: Change index.html
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
    mode: '0644'

- name: Wait for port 80 to become open on the host, don't start checking for 10 seconds
  ansible.builtin.wait_for:
    port: 80
    delay: 10

- name: Check page
  ansible.builtin.uri:
    url: http://localhost
  register: respond

- name: Show respond
  ansible.builtin.debug:
    msg: 'Status code: {{ respond.status }}'
